### ISSUE TITLE
Allow hide parent Floatingbutton on clic on child

### ISSUE THREAD

**Issue by presercomp** [Leondev7/flutter_fab_dialer#10]
I could have an option when building the widget, which will close the "floatingActionButton" when I clicked in addition to the programmed option "onPress"

**Comment by Leondev7** [comment]
I can do it, of course, but can you explain it a little bit more? I want to know why it would be interesting to the project and if more people would use it. Do you want to remove fthe buttons from the view? Do you want to collapse the whole widget?

**Comment by presercomp** [comment]
The idea would be that by pressing a child button of the floatingActionButton, it can be hidden again. On many occasions, you can use a child to navigate to another view, and when you return, the floatingButton is displayed
