### ISSUE TITLE
Allow for not animating the main FAB or animating it differently so that different icons don't look weird

### ISSUE THREAD

**Issue by GroovinChip** [Leondev7/flutter_fab_dialer#11]
When an icon other than Icons.add is used on the main FAB, it looks pretty wonky. Take Icons.menu, for example. Before the FAB is clicked, the icon is on its side. When clicked, it tilts on an angle.

**Comment by GroovinChip** [comment]
Just checked out your link, I don't see any indication of the change?

**Comment by shoxter** [comment]
I'm working on it now. I'll release it sometime today.

**Comment by GroovinChip** [comment]
Nice! Thanks very much.

**Comment by shoxter** [comment]
The fix for this is now live here:

https://pub.dartlang.org/packages/fab_dialer
