### ISSUE TITLE
Allow using images

### ISSUE THREAD

**Issue by oneplusseven** [Leondev7/flutter_fab_dialer#9]
Hello, thanks for developing this plugin. I was wondering if it would be possible to add items with images (not only icons). I was imagining something like this example in the [Material Design](https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions)'s  website:

![](https://material.io/design/assets/16wHIILgWlw7qpoZua_8X_3eWdTMlxFPk/fab-transitions-speeddial-do-contacts.png)

**Comment by Leondev7** [comment]
Thanks for the idea. The problem it's that I don't think flutter's FAB does have a constructor for passing images as background. I'll look into it.
